Repository team-dudoji/dudoji-backend, pull requests merged in 2025-04, with the labels that each got.

#24 Feature/issue 23
  build.gradle
  src/main/java/com/dudoji/spring/config/JwtAuthenticationFilter.java
  src/main/java/com/dudoji/spring/config/SecurityBeansConfig.java
  src/main/java/com/dudoji/spring/config/WebSecurityConfig.java
  src/main/java/com/dudoji/spring/controller/KakaoLoginController.java
  src/main/java/com/dudoji/spring/controller/MainController.java
  src/main/java/com/dudoji/spring/models/dao/UserDao.java
  src/main/java/com/dudoji/spring/models/domain/JwtProvider.java
  src/main/java/com/dudoji/spring/models/domain/PrincipalDetails.java
  src/main/java/com/dudoji/spring/models/domain/TokenInfo.java
  src/main/java/com/dudoji/spring/service/KakaoService.java
  src/main/resources/application.yml
Labels: feature

#30 feature(Step file) : api 일관성을 맞추고, dao 에러를 수정했습니다.
  src/main/java/com/dudoji/spring/controller/UserStepController.java
  src/main/java/com/dudoji/spring/models/dao/UserStepDao.java
Labels: bug

#33 Refactor/issue 32
  .gitignore
  build.gradle
  src/main/java/com/dudoji/spring/config/DotEnvConfig.java
  src/main/java/com/dudoji/spring/models/DBConnection.java
  src/main/java/com/dudoji/spring/models/domain/JwtProvider.java
  src/main/resources/application.yml
Labels: refactor

#34 Feature/issue 31
  build.gradle
  src/main/java/com/dudoji/spring/config/WebSecurityConfig.java
  src/main/java/com/dudoji/spring/controller/LoginController.java
  src/main/java/com/dudoji/spring/controller/MainController.java
  src/main/java/com/dudoji/spring/controller/MapSectionController.java
  src/main/java/com/dudoji/spring/controller/UserStepController.java
  src/main/java/com/dudoji/spring/dto/MapSectionResponseDto.java
  src/main/java/com/dudoji/spring/dto/UserStepsRequestDto.java
  src/main/java/com/dudoji/spring/models/dao/MapSectionDao.java
  src/main/java/com/dudoji/spring/service/MapSectionService.java
Labels: feature

#36 Feature/issue 35
  src/main/java/com/dudoji/spring/controller/UserInfoController.java
  src/main/java/com/dudoji/spring/models/dao/UserDao.java
  src/main/java/com/dudoji/spring/models/domain/User.java
  src/main/java/com/dudoji/spring/security/PrincipalOauth2UserService.java
  src/main/java/com/dudoji/spring/service/UserInfoService.java
Labels: feature

#38 feature/ISSUE-37
  src/main/java/com/dudoji/spring/controller/KakaoLoginController.java
Labels: bug
