Repository team-dudoji/dudoji-backend, pull requests merged in 2025-07, with the labels that each got.

#85 Feature/issue 84
  src/main/java/com/dudoji/spring/controller/FollowController.java
  src/main/java/com/dudoji/spring/controller/UserInfoController.java
  src/main/java/com/dudoji/spring/controller/UserProfileController.java
  src/main/java/com/dudoji/spring/dto/user/UserProfileDto.java
  src/main/java/com/dudoji/spring/dto/user/UserSimpleDto.java
  src/main/java/com/dudoji/spring/models/dao/FollowDao.java
  src/main/java/com/dudoji/spring/models/dao/LikesDao.java
  src/main/java/com/dudoji/spring/models/dao/PinDao.java
  src/main/java/com/dudoji/spring/models/dao/UserDao.java
  src/main/java/com/dudoji/spring/models/dao/UserWalkDistanceDao.java
  src/main/java/com/dudoji/spring/models/domain/User.java
  src/main/java/com/dudoji/spring/service/FollowService.java
  src/main/java/com/dudoji/spring/service/UserInfoService.java
Labels: feature

#86 Implement mission achievement and quest system with corresponding ser…
  src/main/java/com/dudoji/spring/controller/LandmarkController.java
  src/main/java/com/dudoji/spring/controller/MissionController.java
  src/main/java/com/dudoji/spring/dto/mission/AchievementDto.java
  src/main/java/com/dudoji/spring/dto/mission/QuestDto.java
  src/main/java/com/dudoji/spring/models/dao/MissionDao.java
  src/main/java/com/dudoji/spring/models/dao/PinDao.java
  src/main/java/com/dudoji/spring/models/domain/mission/Achievement.java
  src/main/java/com/dudoji/spring/models/domain/mission/MissionUnit.java
  src/main/java/com/dudoji/spring/models/domain/mission/Quest.java
  src/main/java/com/dudoji/spring/models/domain/mission/QuestType.java
  src/main/java/com/dudoji/spring/service/mission/DailyMovementQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/DailyPinQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/FogAchievementChecker.java
  src/main/java/com/dudoji/spring/service/mission/LandmarkAchievementChecker.java
  src/main/java/com/dudoji/spring/service/mission/LandmarkCountQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/MissionChecker.java
  src/main/java/com/dudoji/spring/service/mission/MissionService.java
  src/main/java/com/dudoji/spring/service/mission/NewLandmarkQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/TotalMovementAchievementChecker.java
  src/main/resources/static/sql/data.sql
  src/main/resources/static/sql/schema.sql
Labels: feature

#79 Feature/issue 77
  src/main/java/com/dudoji/spring/config/WebConfig.java
  src/main/java/com/dudoji/spring/config/WebSecurityConfig.java
  src/main/java/com/dudoji/spring/controller/FollowController.java
  src/main/java/com/dudoji/spring/controller/ImageStorageController.java
  src/main/java/com/dudoji/spring/controller/MapSectionController.java
  src/main/java/com/dudoji/spring/controller/PinController.java
  src/main/java/com/dudoji/spring/controller/PinSkinController.java
  src/main/java/com/dudoji/spring/controller/RevealCircleController.java
  src/main/java/com/dudoji/spring/controller/UserWalkDistanceController.java
  src/main/java/com/dudoji/spring/dto/PinSkinDto.java
  src/main/java/com/dudoji/spring/dto/PinSkinSimpleDto.java
  src/main/java/com/dudoji/spring/dto/pin/PinRequestDto.java
  src/main/java/com/dudoji/spring/dto/pin/PinResponseDto.java
  src/main/java/com/dudoji/spring/models/dao/PinSkinDao.java
  src/main/java/com/dudoji/spring/models/domain/Pin.java
  src/main/java/com/dudoji/spring/models/domain/PinSkin.java
  src/main/java/com/dudoji/spring/service/ImageStorageService.java
  src/main/java/com/dudoji/spring/service/PinSkinService.java
  src/main/resources/static/js/landmarks-management.js
  src/main/resources/static/js/pinskins-management.js
  src/main/resources/static/sql/schema.sql
  src/main/resources/templates/admin_pinskins.html
  src/test/java/com/dudoji/spring/dao/PinSkinDaoTest.java
Labels: feature

#89 Feature/issue 87
  src/main/java/com/dudoji/spring/controller/skin/CharacterSkinController.java
  src/main/java/com/dudoji/spring/controller/skin/PinSkinController.java
  src/main/java/com/dudoji/spring/dto/skin/CharacterSkinDto.java
  src/main/java/com/dudoji/spring/dto/skin/CharacterSkinSimpleDto.java
  src/main/java/com/dudoji/spring/dto/skin/PinSkinDto.java
  src/main/java/com/dudoji/spring/dto/skin/PinSkinSimpleDto.java
  src/main/java/com/dudoji/spring/models/dao/skin/CharacterSkinDao.java
  src/main/java/com/dudoji/spring/models/dao/skin/PinSkinDao.java
  src/main/java/com/dudoji/spring/models/domain/skin/CharacterSkin.java
  src/main/java/com/dudoji/spring/models/domain/skin/PinSkin.java
  src/main/java/com/dudoji/spring/service/skin/CharacterSkinService.java
  src/main/java/com/dudoji/spring/service/skin/PinSkinService.java
  src/main/resources/static/js/characterskins-management.js
  src/main/resources/static/sql/schema.sql
  src/main/resources/templates/admin_characterskins.html
  src/test/java/com/dudoji/spring/dao/PinSkinDaoTest.java
Labels: feature

#92 Feature/issue 91
  src/main/java/com/dudoji/spring/util/log/SlackAppender.java
  src/main/resources/logback.xml
Labels: feature

#100 Fix/issue 99
  src/main/resources/static/js/characterskins-management.js
  src/main/resources/static/js/landmarks-management.js
  src/main/resources/static/js/pinskins-management.js
  src/main/resources/templates/admin_characterskins.html
  src/main/resources/templates/admin_landmarks.html
  src/main/resources/templates/admin_pinskins.html
Labels: fix

#102 Feature/issue 101
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/sqldialects.xml
  src/main/java/com/dudoji/spring/controller/KakaoLoginController.java
  src/main/java/com/dudoji/spring/controller/skin/PinSkinController.java
  src/main/java/com/dudoji/spring/dto/pin/PinRequestDto.java
  src/main/java/com/dudoji/spring/dto/pin/PinResponseDto.java
  src/main/java/com/dudoji/spring/models/dao/PinDao.java
  src/main/java/com/dudoji/spring/models/domain/Pin.java
  src/main/resources/static/sql/schema.sql
Labels: feature

#103 Feature/issue 65
  Dockerfile
Labels: feature

#107 Feature/issue 106
  src/main/java/com/dudoji/spring/controller/LandmarkController.java
  src/main/resources/static/js/characterskins-management.js
  src/main/resources/static/js/items-management.js
  src/main/resources/static/js/landmarks-management.js
  src/main/resources/static/js/pinskins-management.js
  src/main/resources/templates/admin_landmarks.html
Labels: feature

#111 featureISSUE-110 : checker 업데이트
  src/main/java/com/dudoji/spring/models/dao/LandmarkDao.java
  src/main/java/com/dudoji/spring/models/dao/UserWalkDistanceDao.java
  src/main/java/com/dudoji/spring/service/mission/DailyMovementQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/LandmarkCountQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/NewLandmarkQuestChecker.java
  src/main/java/com/dudoji/spring/service/mission/TotalMovementAchievementChecker.java
  src/main/resources/static/sql/data.sql
  src/test/java/com/dudoji/spring/MissionTest.java
Labels: feature

#109 feature/ISSUE-108 범위로 랜드마크 받아오기
  src/main/java/com/dudoji/spring/controller/LandmarkController.java
  src/main/java/com/dudoji/spring/models/dao/LandmarkDao.java
  src/main/java/com/dudoji/spring/service/LandmarkService.java
Labels: feature

#115 feature/ISSUE-114 : 좋아요 순으로 Pin Pageable 기능 구현
  src/main/java/com/dudoji/spring/controller/PinController.java
  src/main/java/com/dudoji/spring/dto/pin/PinResponseDto.java
  src/main/java/com/dudoji/spring/models/dao/PinDao.java
  src/main/java/com/dudoji/spring/models/domain/Pin.java
  src/main/java/com/dudoji/spring/service/PinService.java
  src/test/java/com/dudoji/spring/dao/PinDaoTest.java
Labels: feature, refactor

#118 Feature/issue 116
  src/main/java/com/dudoji/spring/config/UserAgentFilter.java
  src/main/resources/static/admin/js/characterskins-management.js
  src/main/resources/static/admin/js/items-management.js
  src/main/resources/static/admin/js/landmarks-management.js
  src/main/resources/static/admin/js/pinskins-management.js
  src/main/resources/static/admin/style/base-style.css
  src/main/resources/static/admin/style/modal-style.css
  src/main/resources/static/admin/style/table-style.css
  src/main/resources/templates/admin_characterskins.html
  src/main/resources/templates/admin_items.html
  src/main/resources/templates/admin_landmarks.html
  src/main/resources/templates/admin_pinskins.html
  src/main/resources/templates/joinForm.html
  src/main/resources/templates/login.html
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/main.html
Labels: feature

#120 feature/ISSUE-119 : UserDao 쿼리문 수정
  src/main/java/com/dudoji/spring/models/dao/UserDao.java
Labels: feature, refactor

#123 feature/ISSUE-121: 랜드마크 검색 기능 구현
  src/main/java/com/dudoji/spring/controller/LandmarkController.java
  src/main/java/com/dudoji/spring/models/dao/LandmarkDao.java
  src/main/java/com/dudoji/spring/service/LandmarkService.java
Labels: feature
